---
title: "Exercise 4"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 4data}
inmates <-
  here::here("data", "inmates.csv") %>%
  read_csv(col_names = TRUE,
           cols(state = col_factor(),
                year = col_factor())) %>%
  janitor::clean_names() %>%
  select(prison, educ, af_am, age, year, state, ca9, ca10, ca11) %>% 
  sample_frac(1/10)
```

### (a)

```{r 4a}
inmates %>% 
  lm(prison ~ educ + age + af_am + state + year, data = .) %>% 
  broom::tidy() %>% 
  slice(1:4)
```

### (b)

### (c)

```{r 4c}
# First stage results
# inmates %$% 
#   lm(educ ~ ca9 + ca10 + ca11 + af_am + year + state) %>% 
#   tidy() %>% 
#   slice(1:4)

# ols_inst <- 
inmates %>% 
  lm(educ ~ ca9 + ca10 + ca11 + af_am + year + state, data = .) %>% 
  car::linearHypothesis(c("ca9", "ca10", "ca11"))
```

### (d)

```{r 4d}
inmates %>% 
  AER::ivreg(prison ~ educ + af_am + age + year + state |
          ca9 + ca10 + ca11 + af_am + age + year + state,
          data = .) %>% 
  broom::tidy() %>% 
  slice(1:4)
```



