---
title: "Exercise 5"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 5data}
democracy <- 
  here::here("data", "democracy_income.csv") %>% 
  read_csv(col_names = TRUE,
           cols(
             CountryCode = col_factor(),
             YearOrder = col_factor()
           )) %>% 
  janitor::clean_names() %>% 
  rename(world_income = worldincome)

```

### (a)

```{r 5a}
democracy %>% 
  lm(democracy_fh ~ dplyr::lag(log_gdp, 1), .) %>% 
  jtools::summ(digits = 4)

```

### (b)

```{r 5b}
democracy %>% 
  plm::plm(democracy_fh ~ dplyr::lag(log_gdp, 1) + year_order,
      data = ., index = "country_code", model = "within") %>% 
  summary()
```


### (c)

```{r 5c}

democracy %>% 
  group_by(country_code) %>% 
  mutate(lag_world_income = dplyr::lag(world_income)) %>% 
  ungroup() %>% 
  mutate(lag_log_gdp = dplyr::lag(log_gdp, 1)) %>% 
  plm::plm(lag_log_gdp ~ lag_world_income + country_code + year_order,
      data = ., index = "country_code", model = "within") %>% 
  summary()
```

### (d)

```{r 5d}
democracy %>% 
  group_by(country_code) %>% 
  mutate(lag_world_income = dplyr::lag(world_income)) %>% 
  ungroup() %>% 
  mutate(lag_log_gdp = dplyr::lag(log_gdp, 1)) %>% 
  AER::ivreg(democracy_fh ~ lag_log_gdp + country_code + year_order | 
          lag_world_income + country_code + year_order,
        data = .) %>% 
  broom::tidy() %>% 
  slice(1:2)
```



