---
title: "Exercise 3"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 3data}
fish <- 
  here::here("data", "fishdata.csv") %>% 
  read_csv() %>% 
  janitor::clean_names()
```

## (a)

```{r 3a}
curve(10*x^(-3/2), xlim = c(0, 10), ylim = c(0,4), 
      main = "Supply and Demand", xlab = "Quantity", ylab = "Price")

curve(1/3*x^(3/2), xlim = c(0, 10), ylim = c(0,4), 
      add = TRUE)

curve(20*x^(-3/2), xlim = c(0, 10), ylim = c(0,4), 
      add = TRUE, col = "red")

segments(y0 = -1, y1 = 10 * 30 ^ (-1/2), x0 = 30^(1/3), x1 = 30^(1/3), lty = 2)

segments(x0 = -1, x1 = 30^(1/3), y0 = 10 * 30 ^ (-1/2), y1 = 10 * 30 ^ (-1/2), lty = 2)

segments(y0 = -1, y1 = 20 * 60 ^ (-1/2), x0 = 60^(1/3), x1 = 60^(1/3), 
         col ="red", lty = 2)

segments(x0 = -1, x1 = 60^(1/3), y0 = 20 * 60 ^ (-1/2), y1 = 20 * 60 ^ (-1/2), 
         lty = 2, col = "red")

```

## (b)

```{r 3b}
fish %>% 
  lm(qty ~ price, .) %>% 
  jtools::summ(digits = 4)
```

## (c)

```{r 3c}
# First stage results
fish %$% 
  lm(price ~ stormy, .) %>% 
  jtools::summ(digits = 4)

fish %$% 
  AER::ivreg(qty ~ price | stormy, data = .) %>% 
  summary(digits = 4)
```

## (d)

```{r 3d}
# first stage
fish %>% 
  lm(price ~ stormy + day1 + day2 + day3 + day4 + rainy + cold, .) %>% 
  jtools::summ(digits = 4)

fish %>% 
  AER::ivreg(qty ~ price + day1 + day2 + day3 + day4 + cold + rainy | 
          stormy + day1 + day2 + day3 + day4 + cold + rainy,
        data = .) %>% 
  summary()

```



